package org.dclab.utils;
import java.io.FileOutputStream;
import java.util.Date;

import com.itextpdf.text.Anchor;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chapter;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.List;
import com.itextpdf.text.ListItem;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Section;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

/**
 * Created by zhaoz on 2016/8/18.
 */
public class PDFWriter {
    private static Font bigFont = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);
    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.NORMAL, BaseColor.RED);
    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16, Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD);

    public static void main(String[] args) {
        try {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream("sample.pdf"));
            document.open();
            addTitle(document);
            addContent(document);
            document.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static void addTitle(Document document)  throws DocumentException {
        Paragraph titlePara = new Paragraph();
        
        addEmptyLine(titlePara, 1);
        titlePara.setAlignment(Element.ALIGN_CENTER);
        titlePara.add(new Paragraph("考生答卷", bigFont));
        
        addEmptyLine(titlePara, 1);
        // Will create: Report generated by: _name, _date
        titlePara.add(new Paragraph("专业： 软件工程"+ "\t科目： 政治" + "\t考生： " + System.getProperty("user.name") ,smallBold));

        titlePara.add(new Paragraph("81分", redFont));
        document.add(titlePara);       
    }

    private static void addContent(Document document) throws DocumentException {
        Anchor anchor = new Anchor("简答题", bigFont);
        anchor.setName("First Chapter");

        // Second parameter is the number of the chapter
        Chapter chapter = new Chapter(new Paragraph(anchor), 1);

        Paragraph topic = new Paragraph("1. “苟利国家生死以” 下一句是什么？", subFont);
        Section section1 = chapter.addSection(topic);

        // add a list
        createList(section1);
        Paragraph paragraph = new Paragraph();
        addEmptyLine(paragraph, 5);
        
        // add a table
        createTable(section1);

        // now add all this to the document
        document.add(chapter);

    }

    private static void createTable(Section subCatPart)
            throws BadElementException {
        PdfPTable table = new PdfPTable(3);

        // t.setBorderColor(BaseColor.GRAY);
        // t.setPadding(4);
        // t.setSpacing(4);
        // t.setBorderWidth(1);

        PdfPCell c1 = new PdfPCell(new Phrase("Table Header 1"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Table Header 2"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Table Header 3"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        table.setHeaderRows(1);

        table.addCell("1.0");
        table.addCell("1.1");
        table.addCell("1.2");
        table.addCell("2.1");
        table.addCell("2.2");
        table.addCell("2.3");

        subCatPart.add(table);

    }

    private static void createList(Section section) {
        List list = new List(true, false, 10);
        list.add(new ListItem("岂因祸福避趋之"));
        list.add(new ListItem("谈笑风生又一年"));
        list.add(new ListItem("人间正道是沧桑"));
        section.add(list);
    }

    private static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }

}
